# Kernel SVM

## Importing the libraries

In [41]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [42]:
dataset = pd.read_csv('telecom_churn.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [43]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 3] = le.fit_transform(X[:, 3])

In [44]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

## Splitting the dataset into the Training set and Test set

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [46]:
print(X_train)

[[67 415 0 ... 9 2.59 1]
 [101 415 0 ... 5 2.89 1]
 [91 510 1 ... 3 2.67 0]
 ...
 [93 510 1 ... 2 3.0 1]
 [91 415 0 ... 3 2.67 3]
 [130 408 1 ... 2 4.56 5]]


In [47]:
print(y_train)

[False False False ...  True False  True]


In [48]:
print(X_test)

[[92 415 1 ... 5 2.51 0]
 [112 510 0 ... 3 2.7 2]
 [69 510 0 ... 4 3.38 3]
 ...
 [89 415 0 ... 1 3.32 3]
 [54 408 0 ... 7 2.62 2]
 [70 415 0 ... 4 2.78 1]]


In [49]:
print(y_test)

[False False False False  True  True  True False False False False False
 False False  True False False False False False  True False False False
 False False False False False False False False False False  True False
  True False False  True False  True  True  True False False False False
 False False  True False False False False False False False False  True
  True False False False False False False False  True False False False
 False False False False False False  True False False False False False
 False False  True False  True False False False False False False False
 False False False False False False  True False False False False False
  True False False False False False False False False False False False
  True False False False False False False False False False False False
 False False False False False False  True False False False  True False
 False False False False False False False False False False False False
 False False  True False False False  True False Fa

## Feature Scaling

In [50]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [51]:
print(X_train)

[[-0.84138829 -0.53000127 -0.32217788 ...  1.85266441 -0.23301487
  -0.42370879]
 [ 0.01041622 -0.53000127 -0.32217788 ...  0.21567745  0.16272454
  -0.42370879]
 [-0.24011452  1.69868521  3.10387541 ... -0.60281603 -0.12748436
  -1.18492249]
 ...
 [-0.19000837  1.69868521  3.10387541 ... -1.01206277  0.30782899
  -0.42370879]
 [-0.24011452 -0.53000127 -0.32217788 ... -0.60281603 -0.12748436
   1.09871861]
 [ 0.73695537 -0.69422028  3.10387541 ... -1.01206277  2.36567391
   2.62114601]]


In [52]:
print(X_test)

[[-0.21506144 -0.53000127  3.10387541 ...  0.21567745 -0.33854538
  -1.18492249]
 [ 0.28600004  1.69868521 -0.32217788 ... -0.60281603 -0.08791042
   0.33750491]
 [-0.79128214  1.69868521 -0.32217788 ... -0.19356929  0.80909891
   1.09871861]
 ...
 [-0.29022066 -0.53000127 -0.32217788 ... -1.42130951  0.72995102
   1.09871861]
 [-1.16707825 -0.69422028 -0.32217788 ...  1.03417093 -0.19344093
   0.33750491]
 [-0.76622907 -0.53000127 -0.32217788 ... -0.19356929  0.01762009
  -0.42370879]]


## Training the Kernel SVM model on the Training set

In [53]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

## Predicting a new result

## Predicting the Test set results

In [54]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[False False]
 [False False]
 [False False]
 ...
 [False False]
 [False False]
 [False False]]


## Making the Confusion Matrix

In [55]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[710   9]
 [ 55  60]]


0.9232613908872902

## Visualising the Training set results

In [56]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_train), y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Kernel SVM (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()

ValueError: ignored

## Visualising the Test set results

In [ ]:
from matplotlib.colors import ListedColormap
X_set, y_set = sc.inverse_transform(X_test), y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 10, stop = X_set[:, 0].max() + 10, step = 0.25),
                     np.arange(start = X_set[:, 1].min() - 1000, stop = X_set[:, 1].max() + 1000, step = 0.25))
plt.contourf(X1, X2, classifier.predict(sc.transform(np.array([X1.ravel(), X2.ravel()]).T)).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('Kernel SVM (Test set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()